root = "."
tmp_dir = "tmp"

[build]
  bin = "./tmp/dsna"
  cmd = "go build -o ./tmp/dsna ."
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor"]
  exclude_file = []
  exclude_regex = []
  exclude_unchanged = true
  follow_symlink = true
  full_bin = ""
  include_dir = []
  include_ext = ["go"]
  kill_delay = "0s"
  log = "air.log"
  send_interrupt = false
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
  clean_on_exit = true
