version: "3.9"

networks:
  a_b_network:
    name: "a_b_network"

services:

  service:
    image: nginx:stable-alpine
    networks:
      - default
      - a_b_network
    deploy:
      labels:
        - dsna.connections=simple-a_service
        - dsna.connections.simple-a_service.network=a_b_network